name: HelloWorld Reusable Workflow

on:
    workflow_call:
        inputs:
            who-to-greet:
                description: 'Who to greet'
                type: string
                required: true
            flag:
                description: 'flag'
                type: boolean
                required: false
                default: true

jobs:
    call-helloworld-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - id: foo
              uses: iacabezasbaculima/reusableworkflows-sandbox/composite/helloworld@main
              with:
                who-to-greet: ${{ inputs.who-to-greet }}
                flag: ${{ inputs.flag }}
            - run: echo random-number "$RANDOM_NUMBER"
              shell: bash
              env:
                RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
      
